name: Node.js CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm install --omit=dev
      - run: npm run build
