name: Node.js CI
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install
        shell: bash
        run: npm install

      - name: Lint
        shell: bash
        run: npm run lint

      - name: build
        shell: bash
        run: npm run build

      - name: Zip artifact for deployment
        run: zip build.zip ./dist/* -r

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build.zip
          retention-days: 5 
